[project]
name = "devenv"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
# DATABASE_URL = { description = "Database connection string", required = true }
DEEPSEEK_API_KEY = { description = "Deepseek v4 pro and flash api key", required = true }
ANTHROPIC_BASE_URL = { default = "https://api.deepseek.com/anthropic", description = "Base URL for Anthropic API" }
ANTHROPIC_AUTH_TOKEN = { description = "Authentication token for Anthropic API", required = true }
ANTHROPIC_MODEL = { default = "deepseek-v4-pro[1m]", description = "Default model for Anthropic API" }
ANTHROPIC_DEFAULT_OPUS_MODEL = { default = "deepseek-v4-pro[1m]", description = "Default model for Anthropic Opus API" }
ANTHROPIC_DEFAULT_SONNET_MODEL = { default = "deepseek-v4-pro[1m]", description = "Default model for Anthropic Sonnet API" }
ANTHROPIC_DEFAULT_HAIKU_MODEL = { default = "deepseek-v4-flash" }
CLAUDE_CODE_SUBAGENT_MODEL = { default = "deepseek-v4-flash" }
CLAUDE_CODE_EFFORT_LEVEL= { default = "max", description = "Effort level for code generation (min, medium, max)" }

[profiles.development]
DEEPSEEK_API_KEY = { description = "Deepseek v4 pro and flash api key", required = true }
ANTHROPIC_BASE_URL = { default = "https://api.deepseek.com/anthropic", description = "Base URL for Anthropic API" }
ANTHROPIC_AUTH_TOKEN = { description = "Authentication token for Anthropic API", required = true }
ANTHROPIC_MODEL = { default = "deepseek-v4-pro[1m]", description = "Default model for Anthropic API" }
ANTHROPIC_DEFAULT_OPUS_MODEL = { default = "deepseek-v4-pro[1m]", description = "Default model for Anthropic Opus API" }
ANTHROPIC_DEFAULT_SONNET_MODEL = { default = "deepseek-v4-pro[1m]", description = "Default model for Anthropic Sonnet API" }
ANTHROPIC_DEFAULT_HAIKU_MODEL = { default = "deepseek-v4-flash" }
CLAUDE_CODE_SUBAGENT_MODEL = { default = "deepseek-v4-flash" }
CLAUDE_CODE_EFFORT_LEVEL= { default = "max", description = "Effort level for code generation (min, medium, max)" }
